name: GitHub Classroom Workflow

on: push

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean up cache
        run: rm -rf ~/.cache/pip
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with: python-version: '3.12'
      - name: Install dependencies
        run: |
          python3 -m venv .venv
          .venv/bin/activate
          export PYRIGHT_PYTHON_FORCE_VERSION=3.12
          pip install -r requirements.txt
          pip install -r requirements.extra.txt
          pip install -Ue .
      - uses: education/autograding@v1
