name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Cache dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: .venv/lib/python3.12/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements.extra.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Create virtual environment
      - name: Create virtual environment
        run: python3 -m venv .venv

      # Install dependencies
      - name: Install dependencies
        run: |
          . .venv/bin/activate
          export PYRIGHT_PYTHON_FORCE_VERSION=3.12

          # Check if packages are installed
          if [ ! -d ".venv/lib/python3.12/site-packages" ] || [ -z "$(ls -A .venv/lib/python3.12/site-packages)" ]; then
            python -m pip install -r requirements.txt
            python -m pip install -r requirements.extra.txt
            python -m pip install -Ue .
          else
            echo "Dependencies already installed, skipping installation."
          fi

      - uses: education/autograding@v1
