name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Set environment variable for Pyright
      - name: Set PYRIGHT_PYTHON_FORCE_VERSION
        run: echo "PYRIGHT_PYTHON_FORCE_VERSION=latest" >> $GITHUB_ENV

      - uses: education/autograding@v1
