name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Cache dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: .venv/lib/python3.12/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements.extra.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Create and activate virtual environment
      - name: Create virtual environment
        run: python3 -m venv .venv

      # Install dependencies
      - name: Install dependencies
        run: |
          .venv/bin/activate
          export PYRIGHT_PYTHON_FORCE_VERSION=3.12
          python -m pip install -r requirements.txt
          python -m pip install -r requirements.extra.txt
          python -m pip install -Ue .

      - uses: education/autograding@v1





